import type { NextPage } from "next";
import { unstable_getServerSession as getServerSession } from "next-auth";
import { useSession, getSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { trpc } from "../utils/trpc";
import { authOptions } from "./api/auth/[...nextauth]";
import { GetServerSideProps } from "next";
import Header from "../components/Header/Header";
import { prisma } from "../server/db/client";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home = () => {
  const { data: session, status } = useSession();
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  // const {
  //   data: userData,
  //   isError,
  //   isLoading,
  // } = trpc.useQuery(["example.getUser", { id: session!.user!.id }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <h1 className="text-4xl font-bold text-center">
          {session?.user?.email}
          {status}
        </h1>
      </div>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <p className="text-2xl text-gray-700">This stack uses:</p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <TechnologyCard
            name="NextJS"
            description="The React framework for production"
            documentation="https://nextjs.org/"
          />
          <TechnologyCard
            name="TypeScript"
            description="Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
            documentation="https://www.typescriptlang.org/"
          />
          <TechnologyCard
            name="TailwindCSS"
            description="Rapidly build modern websites without ever leaving your HTML"
            documentation="https://tailwindcss.com/"
          />
          <TechnologyCard
            name="tRPC"
            description="End-to-end typesafe APIs made easy"
            documentation="https://trpc.io/"
          />
        </div>
        <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        {/* {isLoading && (
          <div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
            <p>Loading...</p>
          </div>
        )}
        {userData && (
          <div className="pt-6 text-2xl text-blue-500 flex flex-col justify-center items-center w-full">
            <p>id: {userData?.id}</p>
            <p>email: {userData?.email}</p>
          </div>
        )}
        {isError && (
          <div className="pt-6 text-2xl text-blue-500 flex flex-col justify-center items-center w-full">
            <p>Something went wrong</p>
          </div>
        )} */}
        <div className="pt-6 text-2xl text-blue-500 flex flex-col justify-center items-center w-full">
          <button
            className="border rounded px-4 py-2"
            onClick={async () => {
              try {
                const users = await fetch("/api/examples");
                console.log(await users.json());
              } catch (error) {
                console.log(error);
              }
            }}
          >
            hello
          </button>
        </div>
      </main>
    </>
  );
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  // const session = await getServerSession(req, res, authOptions);

  // if (!session) {
  //   return {
  //     redirect: {
  //       destination: "api/auth/signin",
  //       permanent: false,
  //     },
  //     props: {},
  //   };
  // }

  return {
    props: {
      session: await getServerSession(req, res, authOptions),
    },
  };
};
export default Home;
